name: Deploy to Prod
on:
    pull_request:
        types:
            - closed
jobs:
    deploy-to-prod:
        if: github.event.pull_request.merged == true
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - name: install dependancies
              run: npm ci
            - name: lint code
              run: npm run lint
